#ifndef MSGPACK_ID_H_
#define MSGPACK_ID_H_

typedef enum Request_ID{

	ServerChallengeRequest_ID = 1000,//1
	HeartBeatRequest_ID,//2
	ArmsConfigRequest_ID,//3
	BuildConfigRequest_ID,//4
	SkillConfigRequest_ID,//5
	RegisterRequest_ID,//6
	SetNameRequest_ID,//7
	BindEmailRequest_ID,//8
	AttackEnemyRequest_ID,//9
	BuildStatusListRequest_ID,//10
	BuildCreateRequest_ID,//11
	BuildUpgradeRequest_ID,//12
	GetMyAssetRequest_ID,//13
	LoginRequest_ID,//14
	GetRandNameRequest_ID,//15
	DressEquipRequest_ID,//16
	UnloadEquipRequest_ID,//17
	SaleGoodsRequest_ID,//18
	LookMarketGoodsRequest_ID,//19
	BuyMarketGoodsRequest_ID,//20
	OpenBoxRequest_ID,//21
	RecruitRequest_ID,//22
	GetRandHeroRequest_ID,//23
	DropHeroRequest_ID,//24
	GetEmailGoodsRequest_ID,//25
	EmailNextPageRequst_ID,//26
	FastFinishRequest_ID,//27
	UpgradeArmTypeRequest_ID,//28
	AppointHeroRequest_ID,//29
	CancelHeroRequest_ID,//30
	SetArmsToHeroRequest_ID,//31
	QuikAttackRequest_ID,//32
	LogoutRequest_ID,//33
	WorldMapNearByRequest_ID,//34
	RandomNewMapRequest_ID,//35
	RandomMoveCityRequest_ID,//36
	SettleMoveCityRequest_ID,//37
	HeroMoveRequest_ID,//38
	WorldMapEnterCityRequest_ID,//39
	WorldMapPlunderResourceRequest_ID,//40
	LookUpCityRequest_ID,//41
	PVEAttackRequest_ID,//42
	KillMonsterRequest_ID,//43
	GetSomePlayerRequest_ID,//44
	StudySkillRequest_ID,//45
	LeaveWordMapRequest_ID,//46
	WorldChannelMsgRequest_ID,//47
	UnionChannelRequest_ID,//48
	PrivateChannelRequest_ID,//49
	FindFriendRequest_ID,//50
	CreateUnionRequest_ID,//51
	LeaveUnionRequest_ID,//52
	AddUnionRequest_ID,//53
	SoldierInfoRequest_ID,//54
	ChangeSoldierCampRequest_ID,//55
	CompleteAtOnceRequest_ID,//56
	msgStartAttack_ID,//57
	msgHeroCastSkillRequest_ID,//58
	msgObjectDieRequest_ID,//59
	msgHeroMoveRequest_ID,//60
	battleSoldier_ID,//61
	battleBuilding_ID,//62
	msgCurBattleInfoRequest_ID,//63
	stateSoldier_ID,//64
	stateBuilding_ID,//65
	msgDfderIsreadyRequest_ID,//66
	msgReportCurStateRequest_ID,//67
	msgSetRallypointRequest_ID,//68
	msgAtkerStopBattleRequest_ID,//69
	SearchGroupRequest_ID,//70
	JoinGroupRequest_ID,//71
	GetJoinRequest_ID,//72
	AcceptJoinRequest_ID,//73
	ExitGroupRequest_ID,//74
	CreateGroupRequest_ID,//75
	PublicGroupMessageRequest_ID,//76
	GetGroupInfoRequest_ID,//77
	GetTop20GroupRequest_ID,//78
	PromotePositionRequest_ID,//79
	UpdateGroupRequest_ID,//80
	SearchUserSimilarRequest_ID,//81
	GetTop50UserResquest_ID//82

}RequestID;

typedef enum Response_ID{

	ServerChallengeResponse_ID = 1000,//1
	VersionInforResponse_ID,//2
	ArmsListResponse_ID,//3
	BuildListResponse_ID,//4
	SkillConfigResponse_ID,//5
	AccountInfoResponse_ID,//6
	SimpleResponse_ID,//7
	MyBuildDataResponse_ID,//8
	MyAttruibuteResponse_ID,//9
	EnemyAttruibuteResponse_ID,//10
	AssetResponse_ID,//11
	DiamondReponse_ID,//12
	RandNameResponse_ID,//13
	EquipResponse_ID,//14
	EquipListResponse_ID,//15
	MarketGoodsResponse_ID,//16
	MarketListResponse_ID,//17
	HeroResponse_ID,//18
	HeroListResponse_ID,//19
	RecruitResponse_ID,//20
	GetMyAssetResponse_ID,//21
	CityLimitListResponse_ID,//22
	EmailSaleResponse_ID,//23
	EmailSaleListResponse_ID,//24
	BattleLogResponse_ID,//25
	MyArmpsLevelResponse_ID,//26
	EnemyStatusResponse_ID,//27
	MyWorldMapCoordResponse_ID,//28
	WorldMapPlayerInfoResponse_ID,//29
	WorldMapResourceResponse_ID,//30
	WorldMapMonsterResponse_ID,//31
	NearByPlayerInfoResponse_ID,//32
	NearByResourceResponse_ID,//33
	NearByMapMonsterResponse_ID,//34
	WorlMapNearByResponse_ID,//35
	NearByAreaResponse_ID,//36
	LookUpCityResponse_ID,//37
	AbleAttackCityResponse_ID,//38
	PVEAttackResponse_ID,//39
	ChangeWorlMapStatusResponse_ID,//40
	PVEWinResponse_ID,//41
	SomePlayerResponse_ID,//42
	WorldChannelMsgResponse_ID,//43
	UnionChannelResponse_ID,//44
	PrivateChannelResponse_ID,//45
	SystemBroadCastResponse_ID,//46
	FindFriendResponse_ID,//47
	MemberResponse_ID,//48
	UnionInfoResponse_ID,//49
	SoldierProcessResponse_ID,//50
	TimeIsUpResponse_ID,//51
	VectorCampInfoResponse_ID,//52
	CampInfoResponse_ID,//53
	soldier_ID,//54
	CompleteAtOnceResponse_ID,//55
	soldiersInfoResponse_ID,//56
	msgStartAtkToAtkerResponse_ID,//57
	msgStartAtkToDfderResponse_ID,//58
	msgHeroCastSkillResponse_ID,//59
	msgObjectDieResponse_ID,//60
	msgHeroMoveResponse_ID,//61
	msgDfderLoginResponse_ID,//62
	msgBeingAtkResponse_ID,//63
	msgCurBattleInfoResponse_ID,//64
	msgDfderIsreadyResponse_ID,//65
	msgDfderLogoutResponse_ID,//66
	msgAtkerLogoutResponse_ID,//67
	msgAskCurStateResponse_ID,//68
	msgReportCurStateResponse_ID,//69
	msgReportBattleResultToAtkerResponse_ID,//70
	msgReportBattleResultToDfderResponse_ID,//71
	msgSetRallypointResponse_ID,//72
	msgRequestAckResponse_ID,//73
	msgAtkerStopBattleToDfderResponse_ID,//74
	msgAtkerStopBattleToAtkerResponse_ID,//75
	SearchGroupResponse_ID,//76
	JoinGroupResponse_ID,//77
	GetJoinRequestResponse_ID,//78
	AcceptJoinResponse_ID,//79
	ExitGroupResponse_ID,//80
	CreateGroupResponse_ID,//81
	PublicGroupMessageResponse_ID,//82
	GetGroupInfoResponse_ID,//83
	GetTop20GroupResponse_ID,//84
	PromotePositionResponse_ID,//85
	UpdateGroupResponse_ID,//86
	SearchUserSimilarResponse_ID,//87
	GetTop50UserResponse_ID//88

}ResponseID;

#define MAX_REQ_NUM 82

#endif /* MSGPACK_ID_H */
