#ifndef MSGPACK_ID_H_
#define MSGPACK_ID_H_

typedef enum Request_ID{

	ServerChallengeRequest_ID = 1000,//1
	HeartBeatRequest_ID,//2
	ArmsConfigRequest_ID,//3
	BuildConfigRequest_ID,//4
	SkillConfigRequest_ID,//5
	RegisterRequest_ID,//6
	SetNameRequest_ID,//7
	BindEmailRequest_ID,//8
	AttackEnemyRequest_ID,//9
	BuildStatusListRequest_ID,//10
	BuildCreateRequest_ID,//11
	BuildUpgradeRequest_ID,//12
	GetMyAssetRequest_ID,//13
	LoginRequest_ID,//14
	GetRandNameRequest_ID,//15
	DressEquipRequest_ID,//16
	UnloadEquipRequest_ID,//17
	SaleGoodsRequest_ID,//18
	LookMarketGoodsRequest_ID,//19
	BuyMarketGoodsRequest_ID,//20
	OpenBoxRequest_ID,//21
	RecruitRequest_ID,//22
	GetRandHeroRequest_ID,//23
	DropHeroRequest_ID,//24
	GetEmailGoodsRequest_ID,//25
	EmailNextPageRequst_ID,//26
	FastFinishRequest_ID,//27
	UpgradeArmTypeRequest_ID,//28
	AppointHeroRequest_ID,//29
	CancelHeroRequest_ID,//30
	QuikAttackRequest_ID,//31
	LogoutRequest_ID,//32
	WorldMapNearByRequest_ID,//33
	RandomNewMapRequest_ID,//34
	RandomMoveCityRequest_ID,//35
	SettleMoveCityRequest_ID,//36
	HeroMoveRequest_ID,//37
	WorldMapEnterCityRequest_ID,//38
	WorldMapPlunderResourceRequest_ID,//39
	LookUpCityRequest_ID,//40
	PVEAttackRequest_ID,//41
	KillMonsterRequest_ID,//42
	GetSomePlayerRequest_ID,//43
	StudySkillRequest_ID,//44
	SetArmsToPartRequest_ID,//45
	LeaveWordMapRequest_ID,//46
	WorldChannelMsgRequest_ID,//47
	UnionChannelRequest_ID,//48
	PrivateChannelRequest_ID,//49
	FindFriendRequest_ID,//50
	CreateUnionRequest_ID,//51
	LeaveUnionRequest_ID,//52
	AddUnionRequest_ID,//53
	SoldierInfoRequest_ID,//54
	ChangeSoldierCampRequest_ID,//55
	CompleteAtOnceRequest_ID,//56
	msgStartAttack_ID,//57
	msgHeroCastSkillRequest_ID,//58
	msgObjectDieRequest_ID,//59
	msgHeroMoveRequest_ID,//60
	battleSoldier_ID,//61
	battleBuilding_ID,//62
	msgCurBattleInfoRequest_ID,//63
	stateSoldier_ID,//64
	stateBuilding_ID,//65
	msgDfderIsreadyRequest_ID,//66
	msgReportCurStateRequest_ID,//67
	msgSetRallypointRequest_ID,//68
	msgAtkerStopBattleRequest_ID,//69
	SearchGroupRequest_ID,//70
	JoinGroupRequest_ID,//71
	GetJoinRequest_ID,//72
	AcceptJoinRequest_ID,//73
	ExitGroupRequest_ID,//74
	CreateGroupRequest_ID,//75
	PublicGroupMessageRequest_ID,//76
	GetGroupInfoRequest_ID,//77
	GetTop20GroupRequest_ID,//78
	PromotePositionRequest_ID,//79
	UpdateGroupRequest_ID,//80
	SearchUserSimilarRequest_ID,//81
	GetTop50UserResquest_ID//82

}RequestID;

typedef enum Response_ID{

	ServerChallengeResponse_ID = 1000,//1
	VersionInforResponse_ID,//2
	ArmsListResponse_ID,//3
	BuildListResponse_ID,//4
	SkillConfigResponse_ID,//5
	AccountInfoResponse_ID,//6
	SimpleResponse_ID,//7
	MyBuildDataResponse_ID,//8
	MyAttruibuteResponse_ID,//9
	EnemyAttruibuteResponse_ID,//10
	AssetResponse_ID,//11
	DiamondReponse_ID,//12
	RandNameResponse_ID,//13
	EquipResponse_ID,//14
	EquipListResponse_ID,//15
	MarketGoodsResponse_ID,//16
	MarketListResponse_ID,//17
	HeroResponse_ID,//18
	HeroListResponse_ID,//19
	RecruitResponse_ID,//20
	GetMyAssetResponse_ID,//21
	CityLimitListResponse_ID,//22
	EmailSaleResponse_ID,//23
	EmailSaleListResponse_ID,//24
	BattleLogResponse_ID,//25
	MyArmpsLevelResponse_ID,//26
	EnemyStatusResponse_ID,//27
	MyWorldMapCoordResponse_ID,//28
	WorldMapPlayerInfoResponse_ID,//29
	WorldMapResourceResponse_ID,//30
	WorldMapMonsterResponse_ID,//31
	NearByPlayerInfoResponse_ID,//32
	NearByResourceResponse_ID,//33
	NearByMapMonsterResponse_ID,//34
	WorlMapNearByResponse_ID,//35
	NearByAreaResponse_ID,//36
	LookUpCityResponse_ID,//37
	AbleAttackCityResponse_ID,//38
	PVEAttackResponse_ID,//39
	ChangeWorlMapStatusResponse_ID,//40
	PVEWinResponse_ID,//41
	SomePlayerResponse_ID,//42
	PartInfoResponse_ID,//43
	WorldChannelMsgResponse_ID,//44
	UnionChannelResponse_ID,//45
	PrivateChannelResponse_ID,//46
	SystemBroadCastResponse_ID,//47
	FindFriendResponse_ID,//48
	MemberResponse_ID,//49
	UnionInfoResponse_ID,//50
	SoldierProcessResponse_ID,//51
	TimeIsUpResponse_ID,//52
	VectorCampInfoResponse_ID,//53
	CampInfoResponse_ID,//54
	soldier_ID,//55
	CompleteAtOnceResponse_ID,//56
	soldiersInfoResponse_ID,//57
	msgStartAtkToAtkerResponse_ID,//58
	msgStartAtkToDfderResponse_ID,//59
	msgHeroCastSkillResponse_ID,//60
	msgObjectDieResponse_ID,//61
	msgHeroMoveResponse_ID,//62
	msgDfderLoginResponse_ID,//63
	msgBeingAtkResponse_ID,//64
	msgCurBattleInfoResponse_ID,//65
	msgDfderIsreadyResponse_ID,//66
	msgDfderLogoutResponse_ID,//67
	msgAtkerLogoutResponse_ID,//68
	msgAskCurStateResponse_ID,//69
	msgReportCurStateResponse_ID,//70
	soldierDamage_ID,//71
	msgReportBattleResultToAtkerResponse_ID,//72
	msgReportBattleResultToDfderResponse_ID,//73
	msgSetRallypointResponse_ID,//74
	msgRequestAckResponse_ID,//75
	msgAtkerStopBattleToDfderResponse_ID,//76
	msgAtkerStopBattleToAtkerResponse_ID,//77
	SearchGroupResponse_ID,//78
	JoinGroupResponse_ID,//79
	GetJoinRequestResponse_ID,//80
	AcceptJoinResponse_ID,//81
	ExitGroupResponse_ID,//82
	CreateGroupResponse_ID,//83
	PublicGroupMessageResponse_ID,//84
	GetGroupInfoResponse_ID,//85
	GetTop20GroupResponse_ID,//86
	PromotePositionResponse_ID,//87
	UpdateGroupResponse_ID,//88
	SearchUserSimilarResponse_ID,//89
	GetTop50UserResponse_ID//90

}ResponseID;

#define MAX_REQ_NUM 82

#endif /* MSGPACK_ID_H */
